# Generated by Django 4.2.16 on 2024-11-26 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('promedio_em', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_ingreso', models.DateField()),
                ('carrera', models.CharField(choices=[('INFORMATICA', 'Informática'), ('ADMINISTRACION', 'Administración'), ('MECANICA', 'Mecánica'), ('CONSTRUCCION', 'Construcción'), ('ROBOTICA', 'Robótica'), ('CONTABILIDAD', 'Contabilidad')], max_length=100)),
            ],
        ),
    ]
